# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Git LFS
      run: |
        brew install git-lfs
        git lfs install

    - name: Fetch WhisperKit tiny model
      run: |
        chmod +x ./fetch_tiny_model.sh
        ./fetch_tiny_model.sh

    - name: Build
      run: swift build
    - name: Test
      run: swift test

